'use strict';

angular.module('app')
  .directive('highChart', function() {
    return {
      restrict: 'E',
      replace: true,
      transclude: true,
      //scope: { title: '@', template: '@', options: '@' },
      template: '<div id="container"></div>',
      controller: function(){
          var targetData =[];
          var actualData =[];
          var value=1000;
          for(var i=0; i<30; i++) {
              value += 500;
              targetData.push(value);
              actualData.push(i%2?(value-650):(value+500));
          }

          Highcharts.chart('container', {

              title: {
                  text: 'Monthly revenue Growth Vs Goal'
              },

              subtitle: {
                  text: 'The revenue generated by the company during the last month'
              },
              xAxis: {
                  min: 1,
                  max: 30,
                  minInterval: 5
              },

              yAxis: {
                  title: {
                      text: 'Revenue ($)'
                  }
              },
              legend: {
                  layout: 'vertical',
                  align: 'right',
                  verticalAlign: 'middle'
              },



              series: [{
                  name: 'Actual Monthly revenue',
                  data: actualData
              }, {
                  name: 'Target Revenue',
                  data: targetData
              }]

          });
      }
    };
  });
